@include('admin.z_header')
<title>Terms & Conditions | Top Shelf Menu</title>
<style>
	.privacy--policy h4 {
		margin:20px 0;
	}
</style>
</head>

<body style="background-color:#fff;">
	<!-- Site Wraper -->
	<div class="home-section"  style="word-wrap:break-word;">

		<div class="row" style="margin-right: 0;">
			@include('admin.z_login_cover')
			<div class="col-md-8 col-sm-6 col-xs-12">
				<div class="row privacy--policy" style="margin-right: 0;">
					<h1 class="text-center">Terms and Conditions</h1>
					<hr style="width:18%;" />
					<p>Welcome to TopShelfMenu.us. The following terms and conditions (the "Agreement") form a binding agreement between you and the TopShelfMenu.us company (owned and operated by TOP SHELF MENU LLC.)&nbsp; which is sometimes referred to as &ldquo;Invoyce,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo; or &ldquo;our.&rdquo; Please review the following terms carefully. By using the Site or any TopShelfMenu.us Services, you are agreeing to these terms, as well as our Privacy Policy (published at http://TopShelfMenu.us/privacy and incorporated here by reference), and all of these terms will govern your use of the Site and our Services. If you do not agree to these terms, you must cease use of the Site and our Services. The term "you" refers to the person accessing or using the Site or our Services, or the company or organization on whose behalf that person accesses the Site or our Services.</p>
					<h4>Our Services</h4>
					<p>TopShelfMenu.us is a website that allows it's users to create, electronically send and get paid for invoices (the "Services") through our website located at https://TopShelfMenu.us and other online areas owned or operated by us, such as our Facebook and mobile phone applications (the "Site").</p>
					<h4>Conditional Use of Our Site and Services</h4>
					<p><span>Your permission to use TopShelfMenu.us&nbsp; is conditioned upon your agreement that you:</span></p>
					<ul class="list--terms">
						<li>are 21 years of age or older;</li>
						<li>will comply with these Terms of Service;</li>
						<li>will not copy or distribute any part of TopShelfMenu.us in any medium without TopShelfMenu.us&rsquo;s prior written authorization;</li>
						<li>will provide accurate information when creating an account or registering for our Services;</li>
						<li>are solely responsible for your User ID and the activity that occurs while signed in to or while using TopShelfMenu.us using your User ID;</li>
						<li>will not use TopShelfMenu.us to collect any personally identifiable information, including account names, email addresses, or other such information, for commercial purposes;</li>
						<li>will not use the communication systems provided by or contacts made on TopShelfMenu.us for any commercial solicitation purposes;</li>
						<li>are solely responsible for your Content submissions, including discussion posts, profile information and links, pictures, and other such content;</li>
						<li>represent that you own or have the necessary licenses, rights, permissions, and consents to use and authorize TopShelfMenu.us to use any and all Content submitted by you to TopShelfMenu.us in accordance with the licenses granted in this Agreement;</li>
						<li>hereby grant each TopShelfMenu.us user, whether using TopShelfMenu.us or an application authorized by TopShelfMenu.us but developed via a third-party developer, a non-exclusive license to access the Content you submit through TopShelfMenu.us and to use, reproduce, distribute, prepare derivative works of, display and perform such Content as permitted through TopShelfMenu.us's functionality and under these Terms of Service;</li>
						<li>will not submit Content that is copyrighted or subject to third party proprietary rights, including privacy, publicity, trade secret, etc., unless you are the owner of such rights or have the appropriate permission from their rightful owner to specifically submit such Content to TopShelfMenu.us; and</li>
						<li>hereby affirm we have the right to determine whether any of your Content submissions are appropriate and comply with these Terms of Service, remove any and/or all of your submissions, and terminate your account with or without prior notice.</li>
					</ul>
					<h4>Your Account And TopShelfMenu.us Profile</h4>
					<p>You will need to register by creating an account with TopShelfMenu.us in order to send invoices from the Site or obtain access to certain Services. When you register, you will obtain&nbsp; unique log-in credentials (a &ldquo;User ID&rdquo;). Access to the TopShelfMenu.us Site and Services is not authorized by any other person or entity using your User ID and you are responsible for preventing such unauthorized use. Individuals and entities whose privilege to access the Site or use the Services has previously been terminated by TopShelfMenu.us may not register for an account, nor may you designate any of those individuals to use your account on your behalf.</p>
					<p>TopShelfMenu.us relies on User IDs to know whether users accessing the Site and using our Services are authorized to do so. If someone accesses our Site or Services using a User ID that we&rsquo;ve issued to you, we will rely on that User ID and will assume that access has been made by you. You are solely responsible for any and all access to the Site or use of the Services by persons using your User ID. Please notify us immediately if you become aware that your User ID is being used without authorization.</p>
					<h4>Non-Confidentiality, Security And Privacy</h4>
					<p>You understand that much of the information that you submit to us is submitted precisely for the purpose of disclosure in a variety of ways by TopShelfMenu.us, and therefore such information is not subject to any confidentiality obligation. Other information, such as credit card information provided in connection with any purchase, is maintained with appropriate privacy and security protections.</p>
					<p>Our Privacy Policy explains how we collect, use and disclose information that pertains to your privacy. The Privacy Policy forms part of our agreement with you and is incorporated in this Agreement by reference. For full details, please refer to our Privacy Policy at https://TopShelfMenu.us/privacy</p>
					<p>Any communications between you and TopShelfMenu.us, such as email or other correspondence, in which you offer suggestions or comments for improving or modifying our Services will be deemed by us to be non-confidential and non-proprietary, and you agree that such information may be used by us without any limitation whatsoever.</p>
					<h4>Rules Regarding Information And Other Content</h4>
					<p>When you use the Site, you can publish and obtain access to various kinds of information and materials, all of which we call "Content." Content also includes information and materials posted to the Site by you. You agree not to revise or obscure Content posted by others (including advertising and promotions authorized by TopShelfMenu.us), and you agree not to post or use any Content in any manner that:</p>
					<ul class="list--terms">
						<li>infringes the copyright, trademark, trade secret, or other intellectual property or proprietary right of others,</li>
						<li>violates the privacy, publicity, or other rights of third parties,</li>
						<li>is unlawful, defamatory, discriminatory, libelous, pornographic, obscene, abusive, threatening, harassing, pornographic, hateful, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate, as determined by TopShelfMenu.us in its sole discretion,</li>
						<li>is false or inaccurate, or</li>
						<li>could damage our company, parent company, sister companies, affiliates, advertisers, or other parties.</li>
					</ul>
					<p>Though we strive to enforce these rules with all of our users, you may be exposed through the Site or Services to Content that violates our policies or is otherwise offensive. You may use the Site and Services at your own risk. We may, but are not obligated to, terminate user accounts and/or remove Content from the Site if we determine or suspect that those accounts or Content violate the terms of this Agreement or the applicable agreement with the offending user(s). We take no responsibility for your exposure to Content on the Site whether it violates our content policies or not.</p>
					<h4>General Rules Of User Conduct</h4>
					<p>It is our goal to make the use of our Site and Services a good experience for all of our users, so you agree not to do any of the following:</p>
					<ul class="list--terms">
						<li>conduct or promote any illegal activities while using the Site or Services;</li>
						<li>upload, distribute or print anything that may be harmful to minors;</li>
						<li>attempt to reverse engineer or jeopardize the correct functioning of the Site or Services, or otherwise attempt to derive the source code of the software (including the tools, methods, processes, and infrastructure) that enables or underlies the Site;</li>
						<li>attempt to gain access to secured portions of the Site or Services to which you do not possess access rights;</li>
						<li>upload or transmit any form of virus, worm, Trojan horse, or other malicious code;</li>
						<li>use the Site or Services to generate unsolicited email advertisements or spam;</li>
						<li>use any automatic or manual process to search or harvest information from the Site or Services, or to interfere in any way with the proper functioning of the Site and Services; or</li>
						<li>impersonate another user.</li>
					</ul>
					<h4>Links To Third Party Sites</h4>
					<p>We don't have control over websites that TopShelfMenu.us may link to. TopShelfMenu.us may contain links to third party websites that are not owned, operated, or controlled by TopShelfMenu.us. Therefore, we cannot and do not assume responsibility for the content, privacy policies, or practices of such websites or the companies that own them. Additionally, we cannot and will not censor or edit the content of any third party site. By using TopShelfMenu.us you expressly relieve us from any and all liability arising from your use of any third party website.</p>
					<h4>Receiving your Funds from Card Transactions</h4>
					<p>Your selected credit card processor will pay you for your transactions, at a schedule communicated to you once your use of Invoyce is approved. (Payouts for your card transactions are typically sent to your bank within 2 days). A certain amount of your funds may be subject to an additional hold period (e.g. Reserve Account) with terms determined by your perceived risk and transaction history. You are responsible for refunds, returns, and liable for customer disputes (chargebacks).</p>
					<h4>Taxes</h4>
					<p>It is your responsibility to determine what, if any, taxes apply to the sale of your goods and services and/or the payments you receive in connection with your use of the Service (&ldquo;Taxes&rdquo;). It is solely your responsibility to assess, collect, report, or remit the correct tax to the proper tax authority. We are not obligated to, nor will we determine whether Taxes apply, or calculate, collect, report, or remit any Taxes to any tax authority arising from any transaction. You acknowledge that we may make certain reports to tax authorities regarding transactions that we process and merchants to which we provide card payment services.</p>
					<p>Pursuant to the Internal Revenue Code, merchant acquiring entities and third party settlement organizations are required to file an information return with the IRS for each calendar year, reporting all payment card transactions and third party network transactions with merchants occurring in that calendar year. You acknowledge that we will report to the Internal Revenue Service the total amount of the payments you receive each calendar year as required by law.</p>
					<h4>Disclaimers of Warranty</h4>
					<p>We provide the Site and Services "as is", "with all faults" and "as available." We and our suppliers and Merchants make no express warranties or guarantees about the Site, Services or Deals. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE AND OUR OFFICERS, DIRECTORS, AGENTS, VENDORS, AND MERCHANTS DISCLAIM IMPLIED WARRANTIES THAT THE SITE AND SERVICES ARE MERCHANTABLE, OF SATISFACTORY QUALITY, ACCURATE, TIMELY, FIT FOR A PARTICULAR PURPOSE OR NEED, OR NON-INFRINGING. WE DO NOT GUARANTEE THAT TopShelfMenu.us WILL MEET YOUR REQUIREMENTS, IS ERROR-FREE, RELIABLE, WITHOUT INTERRUPTION OR AVAILABLE AT ALL TIMES. WE DO NOT GUARANTEE THAT THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF TopShelfMenu.us, INCLUDING ANY SERVICES OR DEALS, WILL BE EFFECTIVE, RELIABLE, ACCURATE OR MEET YOUR REQUIREMENTS. WE MAKE NO WARRANTIES AS TO PRIVACY AND SECURITY OTHER THAN AS EXPRESSLY STATED IN THE PRIVACY POLICY. WE DO NOT GUARANTEE THAT YOU WILL BE ABLE TO ACCESS OR USE THE SITE OR SERVICES AT TIMES OR LOCATIONS OF YOUR CHOOSING. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY A TopShelfMenu.us REPRESENTATIVE SHALL CREATE A WARRANTY. You may have additional consumer rights under your local laws that this contract cannot change.</p>
					<h4>Limitations of Liability</h4>
					<p>YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY DISPUTE WITH US IS TO DISCONTINUE YOUR USE OF TopShelfMenu.us. IN NO EVENT SHALL OUR LIABILITY, OR THE LIABILITY OF OUR AFFILIATES, OFFICERS, DIRECTORS, AGENTS, VENDORS, OR MERCHANTS, FOR ANY AND ALL CLAIMS RELATING TO THE USE OF THE SITE AND SERVICES EXCEED THE TOTAL AMOUNT OF FEES THAT YOU PAID US DURING THE PREVIOUS ONE-YEAR PERIOD FOR THE SPECIFIC SERVICE AT ISSUE. WE, OUR AFFILIATES, OFFICERS, DIRECTORS, AGENTS, VENDORS, AND MERCHANTS, SHALL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING FROM YOUR USE OF, INABILITY TO USE, OR RELIANCE UPON THE SITE AND SERVICES. THESE EXCLUSIONS APPLY TO ANY CLAIMS FOR LOST PROFITS, LOST DATA, LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF WE KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. IF ANY JURISDICTION DOES NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH JURISDICTIONS, OUR LIABILITY, AND THE LIABILITY OF OUR AFFILIATES, OFFICERS, DIRECTORS, AGENTS, VENDORS, AND MERCHANTS, SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
					<h4>Indemnity</h4>
					<p>You agree to defend, indemnify and hold harmless TopShelfMenu.us, its parent company, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to reasonable attorney's fees) arising from: (i) your use of and access to TopShelfMenu.us;; (ii) your violation of any term of these Terms of Service; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that any Content submitted by you causes damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of TopShelfMenu.us.</p>
					<h4>Reservation of Rights and Release</h4>
					<p>TopShelfMenu.us reserves the right, but has no obligation, to monitor, or take any action TopShelfMenu.us deems appropriate regarding disputes that you may have with other customers of ours. To the extent the law permits, you release us from any claims or liability related to any Content posted on the Site and from any claims related to the conduct of any other customers of ours or any Merchants. You hereby waive California Civil Code Section 1542 (if you are a California resident), and any similar provision in any other jurisdiction (if you are a resident of such jurisdiction), which states: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor."</p>
					<h4>Intellectual Property</h4>
					<p>You acknowledge and agree that we and our licensors retain ownership of all intellectual property rights of any kind related to the Site and Services, including applicable copyrights, trademarks and other proprietary rights. We are not granting any license to you under any of those intellectual property rights by virtue of this Agreement, except for the limited right to use the Site and Services in accordance with this Agreement. &ldquo;TopShelfMenu.us&rdquo; is our trademark. Other product and company names that are mentioned on the Site or provided as part of the Services may be trademarks of their respective owners. We reserve all rights that are not expressly granted to you in this Agreement.</p>
					<p>The Content on TopShelfMenu.us, excluding all intellectual property of other sites obtained by way of API and linking and Content posted by our customers, is owned by TopShelfMenu.us. This includes, without limitation, the text, software, scripts, graphics, photos, sounds, interactive features and the trademarks, service marks and logos contained therein ("Marks"). The Marks are owned or licensed to TopShelfMenu.us, subject to copyright and other intellectual property rights under United States law, the law of the jurisdiction where you reside, and and international conventions. Content provided by TopShelfMenu.us is provided to you &ldquo;AS IS&rdquo; for your information and personal use only and may not be used, copied, reproduced, modified, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. We reserve all rights not expressly granted in and to the Site and Services.</p>
					<p>As between you and us, you retain any intellectual property rights in any copyrighted materials and trademarks that are contained in Content that you post to the Site. You grant us an irrevocable, perpetual, non-exclusive, royalty-free, fully paid, worldwide license, with rights to sublicense through multiple levels of sublicensees, to reproduce, make derivative works of, translate, distribute, publicly perform and publicly display in any form or medium, whether now known or later developed, make, use, sell, import, offer for sale, otherwise commercially exploit and exercise any and all such rights, under any and all of your intellectual property rights related to the Content in any manner we choose. If you have any rights to the Content that cannot be licensed to us (such as moral rights in some countries), you unconditionally and irrevocably waive the enforcement of such rights, and all claims and causes of action of any kind against us or related to our customers and partners anywhere in the world, with respect to such rights.</p>
					<h4>Copyright Notice</h4>
					<p>We respect the intellectual property of others, and we ask you to do the same. If you are a copyright owner or an owner's agent and find Content that infringes upon your copyrights, you may submit a notification according to the Digital Millennium Copyright Act. To do so, please provide our Copyright Agent with the following information (see 17 U.S.C 512(c)(3) for further detail) in writing: (1) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (2) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site; (3) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material; (4) Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail; (5) A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (6) A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. TopShelfMenu.us's designated Copyright Agent to receive notifications of claimed infringement can be reached at help@TopShelfMenu.us You acknowledge that if you fail to comply with all of the requirements of this Section, your DMCA notice may not be valid.</p>
					<h4>Electronic Communications</h4>
					<p>The communications between you and TopShelfMenu.us use electronic means, whether you visit the Site or send us emails, or whether TopShelfMenu.us posts notices on the Site or communicates with you via email. For contractual purposes, you (a) consent to receive communications from TopShelfMenu.us in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that TopShelfMenu.us provides to you electronically satisfy any legal requirement that such communications would satisfy if it were in writing. The foregoing does not affect your non-waivable rights.</p>
					<h4>Entire Agreement, Changes to this Agreement and Waivers</h4>
					<p>These Terms of Service, together with the Privacy Policy at https://TopShelfMenu.us/privacy &nbsp;and any other legal notices published by TopShelfMenu.us on the Site or any Drink Voucher, shall constitute the entire agreement between you and TopShelfMenu.us concerning TopShelfMenu.us. We may change the terms of this Agreement from time to time on a going-forward basis, and any such modifications become effective immediately upon being posted to the Site. It is your sole responsibility to check the Site from time to time to view any such changes in the Agreement. If you do not agree to any changes, if and when such changes may be made to the Agreement, you must cease use of the Site and Services. Your use of the Site and Services after any modifications to the Agreement indicates that you agree to such modified Agreement. Any changes to this Agreement (other than as set forth in this paragraph) or waiver of TopShelfMenu.us&rsquo;s rights hereunder shall not be valid or effective except in a written agreement bearing the physical signature of an officer of TopShelfMenu.us. No purported waiver or modification of this Agreement by TopShelfMenu.us via telephonic or email communications shall be valid.</p>
					<h4>General Terms</h4>
					<p>You and we are independent contractors, and nothing in this Agreement creates a partnership, employment relationship or agency. There are no third-party beneficiaries of this Agreement. You may not assign this Agreement or your rights and obligations hereunder, in whole or in part, to any third party without our prior written consent, and any attempt by you to do so will be invalid. Should any part of this Agreement be held invalid or unenforceable, that portion will be construed consistent with applicable law and the remaining portions will remain in full force and effect. Our failure to enforce any provision of this Agreement will not be considered a waiver of the right to enforce such provision. Our rights under this Agreement will survive any termination of this Agreement.</p>
					<p>YOU AND TopShelfMenu.us AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO TopShelfMenu.us MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
					<p>You represent that you are legally able to accept these Terms of Service. You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in this Agreement, and to abide by and comply with this Agreement. And as stated in the Conditional Use of Our Site and Service, above, you affirm that you are, in any case, 13 years of age or older. If you aren't, you must please cease use of TopShelfMenu.us.</p>
					<h4>Notice</h4>
					<p>Any notice required to be given to Invoyce under or related to these Terms must be in writing, addressed as follows:</p>
					<p>TOP SHELF MENU LLC</p>
					<p>2121 6th Avenue N616
						<br>
						Seattle, WA 98121
					</p>
					<p>Last updated: March 4, 2018</p>
				</div>
			</div>
		</div>

		<div class="clearfix"></div>
	</div>
	<!-- Site Wraper End -->

	@include('admin.z_footer')
</body>
</html>